### PR TITLE
fix(dependencies): upgrade to the alpha of remark

### PR DESCRIPTION
**Pull request by travi**
which switches the parser to micromark

for form8ion/remark-remove-greenkeeper-badge#4

### CODE REVIEW

**Comment by travi** [comment]
@wooorm i tried upgrading this project and am seeing what appears to be removal of the blank line between the badge-zone-marker comment and the list of badges. is this a case of what you mention as a notable change to the output in https://github.com/remarkjs/remark/pull/536? the way i read your solution about adding a comment, i wouldn't expect this to be an issue. 

i can dig deeper, but wanted to understand if this is expected behavior before i dig too far

**Comment by wooorm** [comment]
Where are you seeing that / what are you seeing exactly?

**Comment by travi** [comment]
sorry, you can see the diff that the test reports here: https://travis-ci.com/github/form8ion/remark-update-legacy-badge-markers/builds/187968861#L349-L353

you can ignore the `\`s as i think that is just an artifact introduced by the test framework in the diff, but you can see in the removed lines that there was a blank line between the marker command and the first badge in the original markdown, but it is removed in the resulting lines after processing with this plugin. (the `\`s don't impact matching when the blank line is removed from the original content in the test, further suggesting that it is an artifact from the test framework)

**Comment by wooorm** [comment]
It’s a bit hard for me to debug because I don’t know cucumber well, and the tests include [generated stuff](https://github.com/form8ion/remark-update-legacy-badge-markers/blob/c5866e0f4397ebd0826fe0c3ddce52c51009428a/test/integration/features/step_definitions/markers-steps.js#L12-L13), and I don’t know what they contain.

The escapes may be there because remark@next no longer parses references without definitions? 

For the blank line: I read both with plusses, and with minuses, as having blank lines between comments and the paragraph?

**Comment by travi** [comment]
sorry for the delay in follow up on this, but even more sorry for not providing better output here. i certainly shouldnt have sent you digging into my code to have to debug as far as you did.

i did misunderstand the diff in the test output and also the results of the changes that i attempted initially. based on the following output:

before:
```
# project-name

<!-- status badges -->

<!-- consumer badges -->

<!-- contribution badges -->

[![izomohta][puppitede-badge]][jiduce-link]
![museir][izlivmu-badge]
[![datladew](http://jok.at/usu)](http://ked.nc/goc)
![lajcole](http://errobge.lv/doaju)
```

after:
```
# project-name

<!--status-badges start -->

<!--status-badges end -->

<!--consumer-badges start -->

<!--consumer-badges end -->

<!--contribution-badges start -->

<!--contribution-badges end -->

\[\!\[izomohta]\[puppitede-badge]]\[jiduce-link]
\!\[museir]\[izlivmu-badge]
[![datladew](http://jok.at/usu)](http://ked.nc/goc)
![lajcole](http://errobge.lv/doaju)
```

...i agree with your assessment. i still dont read the diff from the test result in a way where both had the blank line, but this console.log clearly confirms that whitespace is not the issue like i thought.

since leaving the references out of the test data didnt cause a problem before, i guess i never went that far in my generation. i do think that fixing the test data will likely resolve this issue. i'll confirm that fairly soon, hopefully.

sorry for the noise. i hope the rollout is mostly going smoothly

**Comment by travi** [comment]
confirmed and fixed. apologies again for burning your time on this, but i really do appreciate you setting me down the right path here

**Comment by wooorm** [comment]
Sweet! Glad I could be of help!

**Pull request merged**
